[package]
name = "coupler"
version = "0.1.0"
authors = ["Micah Johnston <micah@photophore.systems>"]
edition = "2018"
publish = false

[dependencies]
vst3-sys = { path = "api/vst3-sys" }
clap-sys = { git = "https://github.com/glowcoil/clap-sys", rev = "b0dc0b419924a37423b56dc3ef77ec415fa86da2" }
raw-window-handle = "0.3.3"

[workspace]
members = [
    "api/auv2-sys",
    "api/vst3-sys",
    "cargo-coupler",
    "gain",
    "graphics",
    "simd",
    "window",
]
