[workspace]

members = [
    "api/auv2",
    "api/vst2",
    "api/vst2-test",
    "api/vst3",
    "api/vst3-test",
    "gain/*",
    "graphics",
    "plugin",
    "simd",
    "scripts/gen-uuid",
    "window",
]
