[package]
name = "vst3-test"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
vst3 = { path = "../vst3" }

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.9.1"
