[package]
name = "tube-vst3"
version = "0.1.0"
authors = ["Sintel"]
edition = "2021"
publish = false

[package.metadata.coupler]
name = "tube"
formats = ["vst3"]

[lib]
crate-type = ["cdylib"]

[dependencies]
coupler = { workspace = true }
tube = { path = "../.." }
