[package]
name = "tube-vst3"
version = "0.1.0"
authors = ["Micah Johnston <micah@photophore.systems>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
coupler = { workspace = true }
tube = { path = "../.." }
