[package]
name = "plugin-test-vst3"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
plugin = { path = "../../plugin" }
plugin-test = { path = "../core" }
