[package]
name = "gain-auv2"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
coupler = { workspace = true }
gain = { path = "../.." }
