[package]
name = "gain"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]
edition = "2021"
publish = false

[package.metadata.coupler]
name = "Gain"
formats = ["auv2", "clap", "vst3"]

[dependencies]
coupler = { workspace = true }
portlight = { workspace = true }
flicker = { workspace = true }
raw-window-handle = { workspace = true }
